wx:
  ma:
    appId: wxa380df91bda2b909
    secret: ce0074f095049791d3c4879cc604fc33
swagger:
   enable: true
wechat: 
   appid: wx29745c13ddde71aa
   secret: c4ce4651cdd50057e7a168e3239e6378
   appid1: wxd5e3224465422206
   secret1: 92e9030129889dbafcb5a41e0eba7393
   appid2: wxa380df91bda2b909
   secret2: ce0074f095049791d3c4879cc604fc33
spring:
   datasource:
      url: jdbc:mysql://gz-cdb-c0sq6eax.sql.tencentcdb.com:60779/bailun_manicure?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: "#7kfnymAM$Y9-Ntf"
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
gogirl:
  GOGIRL: "http://192.168.1.2/gogirl/"
  GOGIRLMP: "http://127.0.0.1:8088/"
  notifyOrder: "http://t.begogirls.com/gogirl_xcx/pay/notifyOrder"
  notifyCharge: "http://t.begogirls.com/gogirl_xcx/pay/notifyCharge"
  notifyTimesCard: "http://t.begogirls.com/gogirl_xcx/timescard/notifyTimesCard"
  picturePath: "E:\\gogirlPic\\picture\\grouppic\\"
#order
picture-path: E:/upload/grouppic/
picture-prefix: http://192.168.1.2:8092/gogirl_xcx/upload/grouppic/
store-url: http://192.168.1.2:8092/gogirl_xcx/
technician-url: http://192.168.1.2:8092/gogirl_xcx/
customer-url: http://192.168.1.2:8092/gogirl_xcx/
scheduled_template: http://test.begogirls.com/gogirl_mp/wx/template/scheduledTemplateMsg
scheduled_remind: http://test.begogirls.com/gogirl_mp/wx/template/scheduledRemindMsg
to_pay: http://test.begogirls.com/gogirl_mp/wx/template/toBePayMsg
ma_to_pay: http://test.begogirls.com/gogirl_mp/wx/ma/sendWaitForPayMsg
evaluationMsg: http://test.begogirls.com/gogirl_mp/wx/template/evaluationMsg
start-time: "10:00:00"
end-time: "22:30:00"
